PruebaTecnica/PruebaTecnica/Models/ClassCelda.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace PruebaTecnica.Models
{
    public class ClassCelda
    {
        public long x { get; set; }
        public long y { get; set; }
        public long z { get; set; }
        public long v { get; set; }

        public void setCell(long x, long y, long z, long v)
        {
            this.x = x;
            this.y = y;
            this.z = z;
            this.v = v;
        }

        public void setCell(long v)
        {
            this.v = v;
        }

        public long getCell()
        {
            return (this.v);
        }

    }
}

PruebaTecnica/PruebaTecnica/Models/ClassCubo.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;

namespace PruebaTecnica.Models
{
    public class ClassCubo
    {
        List<ClassCelda> celdas { get; set; }
        long n;

        

        public ClassCubo(long dimension)
        {
            n = dimension;
            celdas = new List<ClassCelda>();
            for (long x = 1; x <= n; x++)
            {
                for (long y = 1; y <= n; y++)
                {
                    for (long z = 1; z <= n; z++)
                    {
                        ClassCelda celda = new ClassCelda();
                        celda.setCell(x, y, z, 0);
                        celdas.Add(celda);
                    }
                }
            }
        }

        public void UpdateCell(long x, long y, long z, long v)
        {
            ((celdas.First(c => c.x == x && c.y == y && c.z == z))).setCell(v);
        }        

        public string Query(long x1, long y1, long z1, long x2, long y2, long z2)
        {
            long sum = 0;
            sum = celdas.Where(c => c.x >= x1 && c.y >= y1 && c.z >= z1 && c.x <= x2 && c.y <= y2 && c.z <= z2 && c.v != 0).Sum(c => c.v);
            return sum.ToString();
        }
    }
}

PruebaTecnica/PruebaTecnica/Models/ErrorViewModel.cs
using System;

namespace PruebaTecnica.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

PruebaTecnica/PruebaTecnica/Models/SumCube.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace PruebaTecnica.Models
{
    public class SumCube
    {
        public List<string> output { get; set; }
        public string input { get; set; }
        ClassCubo cubo;

        public SumCube(string input)
        {
            this.input = input;
        }

        public void Summation()
        {
            output = new List<string>();
            string[] lines = input.Split("\r\n");
            int a=0;

            long testCase = long.Parse(lines[0]);
            long j = 1;
            for (long i = 1; i <= testCase; i++)
            {
                string testCaseString = lines[j];

                string[] data = testCaseString.Split(' ');
                long N = long.Parse(data[0]);
                long M = long.Parse(data[1]);
                cubo = new ClassCubo(N);
                for (long operations = 1; operations <= M; operations++)
                {
                    string operationsString = lines[j + operations];
                    string[] operationData = operationsString.Split(' ');
                    if (operationData[0] == "UPDATE")
                    {
                        cubo.UpdateCell(long.Parse(operationData[1]), long.Parse(operationData[2]), long.Parse(operationData[3]), long.Parse(operationData[4]));

                    }
                    else
                    {
                        output.Add(cubo.Query(long.Parse(operationData[1]), long.Parse(operationData[2]), long.Parse(operationData[3]), long.Parse(operationData[4]), long.Parse(operationData[5]), long.Parse(operationData[6])));
                    }
                }

                j = j + M + 1;


            }



            
        }
    }
}

PruebaTecnica/PruebaTecnica/Controllers/CubeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using PruebaTecnica.Models;
namespace PruebaTecnica.Controllers
{
    public class CubeController : Controller
    {
        // GET: Cube
        public ActionResult Index()
        {
            return View();
        }
           
        [HttpPost]
        public ActionResult Result(string data)
        {
            SumCube sumCube = new SumCube(data);
            sumCube.Summation();
            return View(sumCube);
        }
    }
}

PruebaTecnica/PruebaTecnica/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using PruebaTecnica.Models;

namespace PruebaTecnica.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        //public IActionResult Privacy()
        //{
        //    return View();
        //}

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

PruebaTecnica/PruebaTecnica/Views/Cube/Index.cshtml
@{
    ViewData["Title"] = "Index";
}

<form action="/Cube/Result" method="post">
    <div>
        <textarea id="data" name="data" rows="20" cols="100"></textarea>      
    </div>
    <div>
        <button type="submit">Enviar</button>
    </div>
    
</form>

PruebaTecnica/PruebaTecnica/Views/Cube/Result.cshtml
@{
    ViewData["Title"] = "Result";
}
<p><b>Input</b></p>
<p>@{
    WriteLiteral(Model.input.Replace("\r\n", "<br />"));
    }
</p>

<p><b>Ouput</b></p>
<p>@foreach (string line in Model.output)
{
    WriteLiteral(line + "<br />");
}
</p>

PruebaTecnica/PruebaTecnica/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Prueba técnica XpertGroup";
}
 
<div>
    <h1>Cube Summation</h1>


    <p>
        You are given a 3-D Matrix in which each block contains 0 initially. The first block is defined by the coordinate (1,1,1) and the last block is defined by the coordinate (N,N,N). There are two types of queries.
    </p>

<pre>
<code>UPDATE x y z W</code>
</pre>
    <p>
        updates the value of block (x,y,z) to W.
    </p>

<pre>
<code>QUERY x1 y1 z1 x2 y2 z2</code>
</pre>
    <p>

        calculates the sum of the value of blocks whose x coordinate is between x1 and x2 (inclusive), y coordinate between y1 and y2 (inclusive) and z coordinate between z1 and z2 (inclusive).
    </p>

    <p><b>Input Format</b></p>
    <p>
        The first line contains an integer T, the number of test-cases. T testcases follow.<br />
        For each test case, the first line will contain two integers N and M separated by a single space.<br />
        N defines the N * N * N matrix.<br />
        M defines the number of operations.<br />
        The next M lines will contain either
    </p>

<pre>
<code>
 1. UPDATE x y z W
 2. QUERY  x1 y1 z1 x2 y2 z2
</code>
</pre>

    <p><b>Output Format</b></p>
    <p>Print the result for each QUERY.</p>

    <p><b>Constrains</b></p>

    <p>

        1 <= T <= 50<br />
        1 <= N <= 100<br />
        1 <= M <= 1000<br />
        1 <= x1 <= x2 <= N<br />
        1 <= y1 <= y2 <= N<br />
        1 <= z1 <= z2 <= N<br />
        1 <= x,y,z <= N<br />
        -109 <= W <= 109
    </p>

    <p>
        Ing. Ricardo González C.<br />
        <a href="mailto:ricardo.gonzalez@msn.com">ricardo.gonzalez@msn.com</a>
    </p>


</div>

PruebaTecnica/PruebaTecnica/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - PruebaTecnica</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute"
              crossorigin="anonymous"
              integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T"/>
    </environment>
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">PruebaTecnica</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Inicio</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Cube" asp-action="Index">Cube Summation</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <partial name="_CookieConsentPartial" />
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2019 - PruebaTecnica
        </div>
    </footer>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.js"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=">
        </script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.bundle.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-xrRywqdh3PHs8keKZN+8zzc5TX0GRTLCcmivcbNJWm2rs5C8PRhcEn3czEjhAO9o">
        </script>
    </environment>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>